sudo: required
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - expect
before_install:
  - openssl aes-256-cbc -K $encrypted_b2e5b0724a62_key -iv $encrypted_b2e5b0724a62_iv -in client-secret.json.enc -out client-secret.json -d
  - export GOOGLE_CLOUD_PROJECT=shiki-line-bot
install: sudo ./setup_tests.sh && export PATH="${HOME}/google-cloud-sdk/bin:${PATH}"
after_success:
  - mvn clean appengine:deploy
